# Abstract {-}

Since at least its first edition produced by Lewis Thorpe in 1972, Le Roman de Silence has been the fuel for much impassioned debate concerning its mysterious author/narrator, Heldris of Cornwall, and his intended message regarding gender. Some labelling the text an outright misogynist defense of the status quo ([Gaunt 1990](https://www.jstor.org/stable/43151718)) while others revel in the gendered possibilities the text allows its reader to imagine ([Barr 2020](http://doi.org/10.1353/art.2020.0000)). Despite a wide range of interpretations, the common thread running through all of this contentious scholarship is a shared frustration with the inability of modern language translations to convey the abundant polysemy of the text. The rich ambiguity of this thirteenth century Picard verse narrative has plagued translators for decades and has been the source of much scholarly disagreement as inadequate translations can only lead to inadequate analyses ([Pratt 2003](https://www.cambridge.org/core/books/abs/arthurian-literature-xix/humour-in-the-roman-de-silence/02FD0AF72178656EF472359574263262)). However, it is not the fault of editors and translators but rather the limitations of traditional print technology that prevents us from properly engaging with this unique manuscript. Six years after producing her own translation of Silence in 1991, [Regina Psaki](https://www.jstor.org/stable/27869256) expressed frustration with the way print editions — constructed by modern mediators — virtually set medieval texts in stone for modern readers thereby preventing fuller, more complex readings. Calling for a more “diplomatic” (81) approach, Psaki was skeptical of the role “electronic media” (83) might play in resolving the mediation problem, but she insisted that something be done to put this text — in its enigmatic entirety — in the hands of modern readers. Unlike a traditional print edition, a flexible, interactive digital edition could reflect the mutability of Heldris’s elusive language, thereby articulating the ways in which Silence itself translates gender ([Campbell 2019](https://doi.org/10.1215/10829636-7506510)).

In this book, I will build a prototype for such a digital edition.


## Acknowledgements {.unlisted .unnumbered}

Many thanks to my dissertation committee for their ongoing encouragement and criticism, and I am forever indebted to my sister and in-home tech support Lindsay Lee.
