---
title: "Digital edition of _Le Roman de Silence_ (verses 2439-2688)"
subtitle: "Last updated: `r Sys.time()`"
author: "Loren Lee"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::tufte_html_book: default
---

# Hello World

```{r setup, echo=FALSE, message=FALSE}
library(tufte)
library(tidyverse)
library(knitr)

#hide all future R code chunks from output
knitr::opts_chunk$set(echo = FALSE)
```


Hi.

There's about to be some R up in here: `r margin_note("This is a margin note")`

and then there was no more R `r margin_note("A new note?")`

```{r store_text}

df_translations <- tibble(
  Line_all = c(2439:2444),
  `Roche-Mahdi (2007) OF Edition` = c(
    "Quant l’enfes est de tel doctrine",
    "Qu’il entent bien qu’il est mescine,",
    "Ses pere l’a mis a raison,",
    "Se li demostre l’oquoison",
    "Por que on le coile si et cuevre.",
    "“Se li rois Ebayns seüst l’uevre"
  ),
  `Psaki (1991) Translation` = c(
    "When the child had learned enough",
    "to understand that he was a girl,",
    "his father had a talk with him,",
    "and told him the reason",
    "they concealed and hid him.",
    "“If King Ebain knew what"
    
  ),
  Notes = c("",
            "Here's a note",
            "",
            "",
            "",
            "")
) %>%
  mutate(Line = case_when((Line_all + 1 )%% 5 == 0 ~ as.character(Line_all),
                          TRUE ~ "")) 

```



```{r translation_table}
kable(
  df_translations %>% 
    select(Line, `Psaki (1991) Translation`, `Roche-Mahdi (2007) OF Edition`, Notes)
  )

```


