project:
  type: book

book:
  title: "Digital edition of _Le Roman de Silence_ (verses 2439-2688)"
  subtitle: "Last updated: `!r Sys.time()`"
  author: "Loren Lee"
  reader-mode: false
  sidebar:
    search: false
    border: false
    background: "none"
  chapters:
    - index.qmd
    - old-translations.qmd
    - my-translation.qmd
    - interactive-translation.qmd
    - references.qmd

format:
  html:
    css: tufte_updates.css
    toc: false
    author-title: ""
  pdf:
    documentclass: scrreprt
    
    
    
    